### ISSUE TITLE
Incorrect deobfuscated stack traces

### ISSUE THREAD

**Issue by choumx** [ampproject/error-tracker#42]
Might be a bug in Closure Compiler's source maps. 

/cc @jridgewell

**Comment by choumx** [comment]
One example: https://github.com/ampproject/amphtml/issues/16069#issuecomment-397748899

**Comment by erwinmombay** [comment]
i believe this is a bug in closure compilers sourcemap (think justin mentioned it a while ago)

ill take the issue as part of upgrading closure

**Comment by jridgewell** [comment]
Yup, the issue here is CC is producing bad sourcemaps that don't correctly map back to the original code.

**Comment by choumx** [comment]
Couldn't find anything obvious in their [issues queue](https://github.com/google/closure-compiler/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sourcemap+) or in `g/js-compiler-users`. It'd be great if we can follow up with their team with a repro case.

**Comment by choumx** [comment]
Uno mas: https://github.com/ampproject/amphtml/issues/16218#issuecomment-399231576

**Comment by choumx** [comment]
Manually deobfuscating traces will be terrible when public property renaming is enabled with 1-pass. 

Malte suggests that this is caused by our post-compile transforms e.g. prepending AMP_CONFIG, replacing the RTV string (AMP_CONFIG change might be fixable by adding `\n` afterwards). Kris suggested using https://github.com/Rich-Harris/magic-string.

**Comment by jridgewell** [comment]
Oh man, I hadn't even thought about the `AMP_CONFIG` being prepended.

**Comment by cramforce** [comment]
I submitted one fix, but there are at least two more issues to address in https://github.com/ampproject/amphtml/issues/17061

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/issues/17061 is now fixed. Need to wait 3 weeks for the new cuts to include the corrected source maps.

We'll be able to deploy https://github.com/ampproject/error-tracker/pull/55 once https://github.com/ampproject/amphtml/pull/17062 hits production next week.

**Comment by choumx** [comment]
Looks like https://github.com/ampproject/amphtml/issues/17061 was insufficient and this requires more investigation.
